apiVersion: v1
kind: Pod
metadata:
   name: hostinfo
spec:
   containers:
   - name: machineinfo-container01
     image: deepakbedase/machineinfo_env:v1.1.0
     ports:
     - containerPort: 9000
       hostPort: 8000
     env:
       - name: color 
         valueFrom:
           secretKeyRef:
              name: colorsecretprod 
              key: color 
